{% set name = "cryoswath" %}
{% set version = "0.2.1.post4" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/cryoswath-{{ version }}.tar.gz
  sha256: 58a4bc1e6af6ca5b408475dfa20f5690162610e232954661914d87375f9379c1

build:
  entry_points:
    - cryoswath-init = cryoswath.misc:init_project
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.2
    - pip
  run:
    - python >={{ python_min }}
    - dask-core
    - defusedxml
    - geopandas
    - gitpython
    - h5netcdf
    - h5py
    - matplotlib-base
    - numpy
    - packaging
    - pandas
    - pyarrow
    - pyogrio
    - pyproj
    - pytables
    - python-dateutil
    - rasterio
    - rioxarray
    - scikit-learn
    - scipy
    - shapely
    - statsmodels
    - tqdm
    - xarray
    - zarr

test:
  imports:
    - cryoswath
  commands:
    - pip check
    - cryoswath-init --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/j-haacker/cryoswath
  summary: Swath processing toolbox for CryoSat-2
  description: |
    cryoswath is a python package containing processing pipelines, a tool
    library, and some pre-assembled data to retrieve and study CryoSat-2
    data.
    Adaptability lies at its core. The user can access many options simply
    by passing arguments to functions; everything else can be customized
    changing the concerned function or adding a new one.
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  doc_url: https://j-haacker.github.io/cryoswath

extra:
  recipe-maintainers:
    - j-haacker
